#acme_blog:
#    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
#    prefix:   /

# single RESTful
#article:
     #type: rest
     #resource: Acme\BlogBundle\Controller\ArticleController
     #resource: Acme\BlogBundle\Controller\CommentController

# multiple RESTful     
acme_blog:
     type: rest
     resource: "@AcmeBlogBundle/Resources/config/routing.yml"

# single RESTful -- only for TEST     
#homepage:
#     type: rest
#     resource: Acme\BlogBundle\Controller\HomepageController     